### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by mimzivvimzi** [Cury-Sohoni-Lau/browsepad-extension#14]
- [x]  Way to see if I have a note on the page (notification)

- [x]  Input verification and validation for signup/login
    - [x]  Password best practices for password strength
- [x]  Login / logout flow - way to stay logged in through multiple sessions
- [ ]  Extracting metadata from webpage - the url, the title, anything else useful
    - [ ]  Display this info to user
- [ ]  Sharing a note with another account 
- [ ]  Sharable link (view only)
- [ ]  Improvements to UI - using material UI
- [ ]  Basic note text editor - be able to add bullets, bold, italics, headers
    - Use markdown or something else
- [ ]  Profile pictures for users
- [ ]  Color scheme / palette 
    - [ ]  For buttons, text, etc. standardized across app
